ALTER TABLE public.imported_events
ADD COLUMN IF NOT EXISTS timer_started_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS timer_ended_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS timer_seconds INTEGER DEFAULT 0;
